[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qqlh9u8zrelaavqdml06n629l5he8v0u8x5x0awaz7c473p9f7zs5kgrt2f"]

[[validator_account]]
address = "tnam1q9dfxeanu05pn038ancjl3cjpk96me50uuecte43"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "162.55.152.1:26656"

[validator_account.consensus_key]
pk = "tpknam1qzrfvf87em4zrpvufels73cgz9mlqlnzc88cr85thqpzlcmvn4dcz0kn7v2"
authorization = "signam1qzl6pht52fauwt30ycelfv0jtqw9n2lt7j3gq660m5m36pgkg0nhdzft9mejr7ry7lf6xs4pkw3fnc7dd3fj8l9pgh2lkkjjex669jgtzzgfjr"

[validator_account.protocol_key]
pk = "tpknam1qr7qarq573xkttq4qsns5u2vk7zr3zs875v4w47lp739lf8fzsztky0a63h"
authorization = "signam1qq33twl473vx3p00d5dr2jrw59fefmrak6wy9kzlef6rydwqrzhwfcelnmxwtxruw65f4tp73ndyacqehhg3y2kqgay7dyeajh5k5wqtzcee86"

[validator_account.tendermint_node_key]
pk = "tpknam1qze2eswh7wc6rhgte06u6358ntkr5u8p7tff6vpkhh5fhx6k68sj2sys4wu"
authorization = "signam1qzknzgk5mrmxxk9apju4g5532ldu23eedhqrta3pswqm800n5v7uff9tdecnqnr7j577xuayu5g07drc7m98h5wj6es3wy3qn8zsfrsqnldfvm"

[validator_account.eth_hot_key]
pk = "tpknam1qypt8e3ylemsm0jsvva7whezzkar4pkngm75rwdjcd5fyp2k4sq0jxsyp0nfl"
authorization = "signam1q987era8e2avgd2zm5tkmryc47ult8ujj09r3ve9e5p3dftn4uw5kjxtlpgxrjag78e9f7g8k4u4zg3dn5r0l6vjmnupe35nx5nuxlmpqypk55yh"

[validator_account.eth_cold_key]
pk = "tpknam1qyprjfqg09kweudjglpkreasrqt735lg6078m0ulk4tru9pmfu35g2g3hxnm5"
authorization = "signam1qymfzc34dlyxqvhzvyykent4fm9yuz42ulx0ascamm2n9lm09kzcxakd6pw76wux3cuds3mx3c8k2l034mgx03t95usjxmyg9d98yqgeqylrdvw6"

[validator_account.metadata]
email = "blockscape@mway.io"
discord_handle = "marcelmwsblockscape"

[validator_account.signatures]
tpknam1qqlh9u8zrelaavqdml06n629l5he8v0u8x5x0awaz7c473p9f7zs5kgrt2f = "signam1qqqpgr8mnj7ygm7e586zke073pyc423pkk9e3ypaaedv72c8ne7s04pveardy9jmlf3xnqaa74j7vnyw6qc2q3wlyqx4h3ddfyu9ttsqfdlknw"

[[bond]]
source = "tnam1q9dfxeanu05pn038ancjl3cjpk96me50uuecte43"
validator = "tnam1q9dfxeanu05pn038ancjl3cjpk96me50uuecte43"
amount = "1000000"

[bond.signatures]
tpknam1qqlh9u8zrelaavqdml06n629l5he8v0u8x5x0awaz7c473p9f7zs5kgrt2f = "signam1qrnhgsuw20y5cvmzcphsvktd0s94pvwz6kukr4zg6yjlyvgl5e2tnmuy34aqq3wzxv2n5zs0c6rn64tqkejwv8ps32gf2suesksvfzqdp5tdaz"